
###
GET http://localhost:3000/vehicle
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzYWRxdWVAMTIiLCJyb2xlIjoidXNlciIsImV4cCI6MTcyMTE1MzY5Nn0.D0VeWWxIBeRcm4tn_HRruEi434EHwB5SU4hNYd6VOMw
###
GET http://localhost:3000/vehicle/1
Authorization: 
###
POST http://localhost:3000/vehicle
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYmR1bHJhaG1hbkBhbGxpIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzIwNDM0Mjg1fQ.885h7vZHJMcybnA9TKytxdVrO_0iqsSCF1ViCq5g29M 
Content-Type: application/json

{
  "vehicle_id": 2,
  "avalilability":"davailable"
}
###
PUT http://localhost:3000/vehicle/1
Authorization: 
Content-Type: application/json

{
"avalilability":"unavailable"
}
###
DELETE http://localhost:3000/vehicle/1
###
GET http://localhost:3000/specs
###
GET http://localhost:3000/specs/1
###
POST http://localhost:3000/specs
Content-Type: application/json

{
  
  "manufacture": "BMW",
  "model": "nissan",
  "year": "2024",
  "fuel_type": "disel",
  "engine_capacity": "great1.0-1.2 Litre Engines",
  "transmission": "done",
  "color": "blue",
  "seating_capacity": 4,
  "features": "medium"
}
###
PUT http://localhost:3000/specs/1
Content-Type: application/json

{
"year": "July 2024",
"engine_capacity": "great1.0-1.2 Litre Engines",
}
###
DELETE http://localhost:3000/specs/4
###
GET http://localhost:3000/manage
###
GET http://localhost:3000/manage/2
###
POST http://localhost:3000/manage
Content-Type: application/json

{
    "vehicle_id": 3,
    "acquisition_date": "2023-09-09",
    "depreciation_rate": "4%",
    "current_value": "100000000",
    "maintainance_cost": "30000",
    "status": "done"
}
###
PUT http://localhost:3000/manage/4
Content-Type: application/json

{
"status": "done",
"date":"july 10th",
"current_value": "1000000500"
}
###
DELETE http://localhost:3000/manage/7
Authorization:
###
GET http://localhost:3000/customer
###
GET http://localhost:3000/locate/1
###
POST http://localhost:3000/locate
Content-Type: application/json

{
  "name": "Riyadh",
  "address": "323makka",
  "contact_phone": "+323732332"
}
###
PUT http://localhost:3000/locate/1
Content-Type: application/json

{
"address": "50Riyadh"
}
###
DELETE http://localhost:3000/locate/7
###
GET http://localhost:3000/customer

###
GET http://localhost:3000/customer
###
POST http://localhost:3000/customer
Content-Type: application/json

{
  
    
    "subject": "sevice",
    "description": "Am greatful of your prestigeus car service",
    "status": "done"
}
###
PUT http://localhost:3000/customer/1
Content-Type: application/json

{
"address": "50Riyadh"
}
###
DELETE http://localhost:3000/customer/7
###
GET http://localhost:3000/book
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYmR1bHJhaG1hbkBhbGxpIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzIxMjU1NDU4fQ.fM0AgDJWYtsnRVpak-CM2s6dGvufa9YxP3gtLLEY42s
###
GET http://localhost:3000/book/6
###
POST http://localhost:3000/book
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYmR1bHJhaG1hbkBhbGxpIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzIwNzA0MDgzfQ.Pw3CLYbMk7ZZOYJlPclnJkoBP3Qr_pjVKlWzuJz-__M
Content-Type: application/json

{

"full_name":"Abdurahman",
"email":"abdulrahman@gmail.com",
"contact_phone":"+2547634783437"
}
###
PUT http://localhost:3000/manage/3
Content-Type: application/json

{
"acquisition_date": "3 june",
"depreciation_rate": "6%",
}
###
DELETE http://localhost:3000/book
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzYWRxdWVAMTIiLCJyb2xlIjoidXNlciIsImV4cCI6MTcyMTI1NTM3MX0.OClM_moFz6-S-1DzCXDVbf2zqS3PvKeyyQ9keUk9QDs
###
GET http://localhost:3000/payment
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzYWRxdWVAMTIiLCJyb2xlIjoidXNlciIsImV4cCI6MTcyMDcwNDM1Mn0.EvuQqccBHlVo4bocJ2YWJK_ANqTTEDbRnCC6cb7Dciw
###
GET http://localhost:3000/manage

###
PUT http://localhost:3000/book/2
Content-Type: application/json

{
 "total_amount": "70000000"
}
###
POST http://localhost:3000/payment
Content-Type: application/json

{
"full_name":"Abdurahman",
"email":"abdulrahman@gmail.com",
"contact_phone":"+2547634783437"
}
###
PUT http://localhost:3000/payment/8
Content-Type: application/json

{
"full_name":"Abdurahman",
"email":"abdulrahman@gmail.com"
}
###
GET http://localhost:3000/customer
###
POST http://localhost:3000/register
Content-Type: application/json

{
"full_name":"Abdirahman Alli",
"email":"abdirahman@alli",
"contact_phone":"0765433442",
"adress":"Riyadh",
"password":"kms@@17k",
"role":"admin"
}
###
PUT http://localhost:3000/user/10
Content-Type: application/json

{
"full_name":"Abdirahman",
"email":"abdulrahmarn@all",
"contact_phone":"076543344223"
}
###
POST  http://localhost:3000/login
Content-Type: application/json

{
"email":"abdulrahmarn@all",
"password":"kms21"
}

###
GET http://localhost:3000/user/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYmR1bHJhaG1hbkBhbGxpIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzIxMjI2ODc0fQ.CWlwQyttuP25_xe44oh6ugi9HQK1-S6tb6EhGa-NKBw
###
GET http://localhost:3000/user/1

###
DELETE  http://localhost:3000/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYmR1bHJhaG1hbkBhbGxpIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzIwNzEzMzI1fQ.FL4mzmpm3uvcsGEPT3i24290T7-CpqvGGJw-DMY3KZM
###
PUT http://localhost:3000/user/10
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImVtYWlsIjoiYWJkdWxyYWhtYXJuQGFsbCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcyMTI4OTI2NywiZXhwIjoxNzIxMjkyODY3fQ.XKs-ECFsPvWhY5SSs2j6ggCSlBG_424ZCekD_ACJarc
Content-Type: application/json

{
"full_name":"Abdurahman",
"email":"abdulrahman@gmail.com",
"contact_phone":"+2547634783437"
}
###
PUT http://localhost:3000/user/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYmR1bHJhaG1hbkBhbGxpIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzIwNzEzMzI1fQ.FL4mzmpm3uvcsGEPT3i24290T7-CpqvGGJw-DMY3KZM
Content-Type: application/json

{
"full_name":"Abdurahman",
"email":"abdulrahman@gmail.com"
}
###
POST http://localhost:3000/register
Content-Type: application/json

{
"user_id":1,
"email":"sadque@dsghj",
"password":"pass67",
"role":"user"
}
###
POST  http://localhost:3000/login
Content-Type: application/json

{
"email":"sadque@12",
"password":"pass23"
}